# Generated by Django 5.2.7 on 2025-10-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_cita_options_alter_servicio_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
