# Generated by Django 5.2.7 on 2025-10-23 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_carrito_cita_delete_carritoservicio'),
        ('mascotas', '0004_alter_historialveterinario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='mascotas.mascota'),
        ),
    ]
