# Generated by Django 5.2.7 on 2025-10-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cita_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
