# Generated by Django 5.2.7 on 2025-11-03 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_cita_actualizado_en_cita_actualizado_por_and_more'),
        ('mascotas', '0005_historialveterinario_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamiento', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='historial/')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_clinicas', to='citas.cita')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_clinicas', to='mascotas.mascota')),
                ('veterinario', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'veterinario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_clinicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
