# Generated by Django 5.2.7 on 2025-11-04 05:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_notaclinica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'veterinario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('transferencia', 'Depósito/Transferencia')], default='transferencia', max_length=30)),
                ('referencia', models.CharField(max_length=60, unique=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pendiente_verificacion', 'Pendiente de verificación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=30)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('banco', models.CharField(blank=True, max_length=60)),
                ('numero_boleta', models.CharField(blank=True, max_length=60)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='citas.pago'),
        ),
    ]
