--
-- PostgreSQL database dump
--

\restrict 6MN6g90zhqriobiuxOucByK4J5iCi0MfuVgCxBLuBfbCjqkg1OvZvD17Vm2QByf

-- Dumped from database version 14.19 (Ubuntu 14.19-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.19 (Ubuntu 14.19-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE veterinaria_db;
--
-- Name: veterinaria_db; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE veterinaria_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'C.UTF-8';


\unrestrict 6MN6g90zhqriobiuxOucByK4J5iCi0MfuVgCxBLuBfbCjqkg1OvZvD17Vm2QByf
\connect veterinaria_db
\restrict 6MN6g90zhqriobiuxOucByK4J5iCi0MfuVgCxBLuBfbCjqkg1OvZvD17Vm2QByf

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: citas_carrito; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.citas_carrito (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    agregado_en timestamp with time zone NOT NULL,
    servicio_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- Name: citas_carrito_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.citas_carrito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.citas_carrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: citas_cita; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.citas_cita (
    id bigint NOT NULL,
    fecha timestamp with time zone NOT NULL,
    estado character varying(20) NOT NULL,
    notas text NOT NULL,
    creado_en timestamp with time zone NOT NULL,
    servicio_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    mascota_id bigint,
    fecha_fin timestamp with time zone,
    actualizado_en timestamp with time zone NOT NULL,
    actualizado_por_id bigint,
    veterinario_id bigint,
    pago_id bigint
);


--
-- Name: citas_cita_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.citas_cita ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.citas_cita_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: citas_notaclinica; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.citas_notaclinica (
    id bigint NOT NULL,
    fecha timestamp with time zone NOT NULL,
    motivo character varying(120) NOT NULL,
    diagnostico text NOT NULL,
    tratamiento text NOT NULL,
    medicamentos text NOT NULL,
    adjunto character varying(100),
    cita_id bigint,
    mascota_id bigint NOT NULL,
    veterinario_id bigint
);


--
-- Name: citas_notaclinica_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.citas_notaclinica ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.citas_notaclinica_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: citas_pago; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.citas_pago (
    id bigint NOT NULL,
    metodo character varying(30) NOT NULL,
    referencia character varying(60) NOT NULL,
    monto_total numeric(10,2) NOT NULL,
    estado character varying(30) NOT NULL,
    fecha_limite timestamp with time zone,
    banco character varying(60) NOT NULL,
    numero_boleta character varying(60) NOT NULL,
    fecha_pago date,
    notas text NOT NULL,
    comprobante character varying(100),
    creado_en timestamp with time zone NOT NULL,
    actualizado_en timestamp with time zone NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- Name: citas_pago_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.citas_pago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.citas_pago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: mascotas_historialveterinario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mascotas_historialveterinario (
    id bigint NOT NULL,
    fecha date NOT NULL,
    descripcion character varying(200) NOT NULL,
    veterinario character varying(120) NOT NULL,
    diagnostico character varying(200) NOT NULL,
    creado timestamp with time zone NOT NULL,
    mascota_id bigint NOT NULL,
    foto character varying(100)
);


--
-- Name: mascotas_historialveterinario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mascotas_historialveterinario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mascotas_historialveterinario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mascotas_inmunizacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mascotas_inmunizacion (
    id bigint NOT NULL,
    edad_anios smallint NOT NULL,
    rabia boolean NOT NULL,
    dhpp boolean NOT NULL,
    lyme boolean NOT NULL,
    bordetella boolean NOT NULL,
    lepto boolean NOT NULL,
    influenza boolean NOT NULL,
    mascota_id bigint NOT NULL,
    CONSTRAINT mascotas_inmunizacion_edad_anios_check CHECK ((edad_anios >= 0))
);


--
-- Name: mascotas_inmunizacion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mascotas_inmunizacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mascotas_inmunizacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mascotas_mascota; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mascotas_mascota (
    id bigint NOT NULL,
    nombre character varying(80) NOT NULL,
    especie character varying(20) NOT NULL,
    raza character varying(80) NOT NULL,
    sexo character varying(1) NOT NULL,
    fecha_nacimiento date,
    peso_kg numeric(5,2),
    color character varying(60) NOT NULL,
    esterilizado boolean NOT NULL,
    alergias text NOT NULL,
    foto character varying(100),
    creado timestamp with time zone NOT NULL,
    actualizado timestamp with time zone NOT NULL,
    propietario_id bigint NOT NULL,
    codigo_area character varying(6) NOT NULL,
    departamento character varying(100) NOT NULL,
    direccion_completa character varying(255) NOT NULL,
    municipio character varying(100) NOT NULL,
    telefono character varying(20) NOT NULL,
    zona character varying(10) NOT NULL,
    condiciones_actuales text NOT NULL,
    veterinario character varying(120) NOT NULL
);


--
-- Name: mascotas_mascota_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mascotas_mascota ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mascotas_mascota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servicios_servicio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.servicios_servicio (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text NOT NULL,
    precio numeric(8,2) NOT NULL,
    disponible boolean NOT NULL,
    duracion integer NOT NULL,
    imagen character varying(100)
);


--
-- Name: servicios_servicio_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.servicios_servicio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.servicios_servicio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_usuario (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    tipo_usuario character varying(15) NOT NULL,
    telefono character varying(8) NOT NULL,
    fecha_registro timestamp with time zone NOT NULL
);


--
-- Name: usuarios_usuario_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_usuario_groups (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: usuarios_usuario_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_usuario_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_usuario_user_permissions (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: usuarios_usuario_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_usuario_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_veterinarioperfil; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_veterinarioperfil (
    id bigint NOT NULL,
    colegiado character varying(50) NOT NULL,
    especialidades character varying(255) NOT NULL,
    bio text NOT NULL,
    foto character varying(100),
    disponible boolean NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- Name: usuarios_veterinarioperfil_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_veterinarioperfil ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_veterinarioperfil_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_veterinarioperfil_servicios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_veterinarioperfil_servicios (
    id bigint NOT NULL,
    veterinarioperfil_id bigint NOT NULL,
    servicio_id bigint NOT NULL
);


--
-- Name: usuarios_veterinarioperfil_servicios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_veterinarioperfil_servicios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_veterinarioperfil_servicios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
1	cliente
2	veterinario
3	administrador
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
1	2	48
2	2	45
3	2	46
4	2	47
5	3	1
6	3	2
7	3	3
8	3	4
9	3	5
10	3	6
11	3	7
12	3	8
13	3	9
14	3	10
15	3	11
16	3	12
17	3	13
18	3	14
19	3	15
20	3	16
21	3	17
22	3	18
23	3	19
24	3	20
25	3	21
26	3	22
27	3	23
28	3	24
29	3	25
30	3	26
31	3	27
32	3	28
33	3	29
34	3	30
35	3	31
36	3	32
37	3	33
38	3	34
39	3	35
40	3	36
41	3	37
42	3	38
43	3	39
44	3	40
45	3	41
46	3	42
47	3	43
48	3	44
49	3	45
50	3	46
51	3	47
52	3	48
53	3	49
54	3	50
55	3	51
56	3	52
57	3	53
58	3	54
59	3	55
60	3	56
61	3	57
62	3	58
63	3	59
64	3	60
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_usuario
22	Can change user	6	change_usuario
23	Can delete user	6	delete_usuario
24	Can view user	6	view_usuario
25	Can add cita	7	add_cita
26	Can change cita	7	change_cita
27	Can delete cita	7	delete_cita
28	Can view cita	7	view_cita
29	Can add servicio	8	add_servicio
30	Can change servicio	8	change_servicio
31	Can delete servicio	8	delete_servicio
32	Can view servicio	8	view_servicio
33	Can add Servicio en carrito	9	add_carritoservicio
34	Can change Servicio en carrito	9	change_carritoservicio
35	Can delete Servicio en carrito	9	delete_carritoservicio
36	Can view Servicio en carrito	9	view_carritoservicio
37	Can add carrito	10	add_carrito
38	Can change carrito	10	change_carrito
39	Can delete carrito	10	delete_carrito
40	Can view carrito	10	view_carrito
41	Can add cita	11	add_cita
42	Can change cita	11	change_cita
43	Can delete cita	11	delete_cita
44	Can view cita	11	view_cita
45	Can add veterinario perfil	12	add_veterinarioperfil
46	Can change veterinario perfil	12	change_veterinarioperfil
47	Can delete veterinario perfil	12	delete_veterinarioperfil
48	Can view veterinario perfil	12	view_veterinarioperfil
49	Can add Mascota	13	add_mascota
50	Can change Mascota	13	change_mascota
51	Can delete Mascota	13	delete_mascota
52	Can view Mascota	13	view_mascota
53	Can add Entrada de historial	14	add_historialveterinario
54	Can change Entrada de historial	14	change_historialveterinario
55	Can delete Entrada de historial	14	delete_historialveterinario
56	Can view Entrada de historial	14	view_historialveterinario
57	Can add Inmunización	15	add_inmunizacion
58	Can change Inmunización	15	change_inmunizacion
59	Can delete Inmunización	15	delete_inmunizacion
60	Can view Inmunización	15	view_inmunizacion
61	Can add nota clinica	16	add_notaclinica
62	Can change nota clinica	16	change_notaclinica
63	Can delete nota clinica	16	delete_notaclinica
64	Can view nota clinica	16	view_notaclinica
65	Can add pago	17	add_pago
66	Can change pago	17	change_pago
67	Can delete pago	17	delete_pago
68	Can view pago	17	view_pago
\.


--
-- Data for Name: citas_carrito; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.citas_carrito (id, cantidad, agregado_en, servicio_id, usuario_id) FROM stdin;
104	1	2025-11-04 00:55:29.621893-06	2	11
83	2	2025-11-03 14:38:27.042513-06	2	10
\.


--
-- Data for Name: citas_cita; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.citas_cita (id, fecha, estado, notas, creado_en, servicio_id, usuario_id, mascota_id, fecha_fin, actualizado_en, actualizado_por_id, veterinario_id, pago_id) FROM stdin;
12	2025-10-25 13:00:00-06	pendiente		2025-10-27 20:52:11.376244-06	2	11	6	2025-10-25 13:35:00-06	2025-11-03 13:03:06.773368-06	\N	\N	\N
18	2025-11-15 12:08:00-06	pendiente		2025-11-03 18:09:44.374345-06	4	11	6	2025-11-15 13:43:00-06	2025-11-03 18:09:44.374338-06	\N	10	\N
16	2025-11-06 13:00:00-06	completada		2025-11-03 17:28:42.925069-06	5	11	6	2025-11-06 13:55:00-06	2025-11-03 21:41:53.189912-06	9	9	\N
22	2025-11-18 14:45:00-06	cancelada		2025-11-03 20:46:26.20863-06	5	11	6	2025-11-18 15:40:00-06	2025-11-03 21:42:00.12311-06	9	9	\N
26	2025-12-05 10:56:00-06	pendiente		2025-11-03 23:56:53.292402-06	4	11	6	2025-12-05 12:31:00-06	2025-11-03 23:56:53.292395-06	\N	10	1
27	2025-11-27 13:05:00-06	pendiente		2025-11-04 00:05:59.82275-06	4	11	6	2025-11-27 14:40:00-06	2025-11-04 00:05:59.822743-06	\N	10	2
28	2025-11-12 16:08:00-06	pendiente		2025-11-04 00:09:12.148052-06	4	11	6	2025-11-12 17:43:00-06	2025-11-04 00:09:12.148045-06	\N	10	3
29	2025-11-18 10:48:00-06	pendiente		2025-11-04 00:48:27.591612-06	5	11	6	2025-11-18 11:43:00-06	2025-11-04 00:48:27.591605-06	\N	9	4
\.


--
-- Data for Name: citas_notaclinica; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.citas_notaclinica (id, fecha, motivo, diagnostico, tratamiento, medicamentos, adjunto, cita_id, mascota_id, veterinario_id) FROM stdin;
\.


--
-- Data for Name: citas_pago; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.citas_pago (id, metodo, referencia, monto_total, estado, fecha_limite, banco, numero_boleta, fecha_pago, notas, comprobante, creado_en, actualizado_en, usuario_id) FROM stdin;
1	transferencia	MV-11-20251104-CF17	448.00	pendiente_verificacion	2025-11-05 23:56:56.606177-06	Banco industrial	5465123198	2025-11-04		pagos/comprobantepago.png	2025-11-03 23:56:56.607347-06	2025-11-04 00:01:07.952119-06	11
2	transferencia	MV-11-20251104-07D0	448.00	pendiente	2025-11-06 00:06:02.93473-06			\N			2025-11-04 00:06:02.935229-06	2025-11-04 00:06:02.935235-06	11
3	transferencia	MV-11-20251104-6967	448.00	pendiente	2025-11-06 00:09:15.321912-06			\N			2025-11-04 00:09:15.323214-06	2025-11-04 00:09:15.323232-06	11
4	transferencia	MV-11-20251104-EA55	112.00	pendiente	2025-11-06 00:48:30.845257-06			\N			2025-11-04 00:48:30.846259-06	2025-11-04 00:48:30.846273-06	11
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-10-08 12:31:20.943375-06	2	alejandra.1 (cliente)	1	[{"added": {}}]	6	1
2	2025-10-08 12:56:49.771833-06	1	Consulta general	1	[{"added": {}}]	8	1
3	2025-10-08 13:05:39.586806-06	2	Vacunación	1	[{"added": {}}]	8	1
4	2025-10-08 13:37:37.294843-06	3	Desparasitación	1	[{"added": {}}]	8	1
5	2025-10-17 10:22:28.265633-06	1	admin (cliente)	2	[{"changed": {"fields": ["password"]}}]	6	1
6	2025-10-17 10:23:21.825569-06	1	admin (admin)	2	[{"changed": {"fields": ["Email address", "Tipo usuario", "Telefono"]}}]	6	1
7	2025-10-19 18:07:58.603269-06	1	Consulta general	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
8	2025-10-19 18:15:32.787958-06	1	Consulta general	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
9	2025-10-19 18:15:47.666625-06	1	Consulta general	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
10	2025-10-19 22:51:04.355315-06	2	Vacunación	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
11	2025-10-19 22:51:10.944413-06	3	Desparasitación	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
12	2025-10-19 22:53:48.898415-06	4	Cirugía General	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
13	2025-10-20 00:49:14.838328-06	1	Consulta general	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
14	2025-10-20 00:49:42.574116-06	1	Consulta general	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
15	2025-10-20 00:55:46.489846-06	1	Consulta general	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
16	2025-10-20 00:55:55.112186-06	1	Consulta general	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
17	2025-10-20 00:56:50.04458-06	2	Vacunación	2	[]	8	1
18	2025-10-20 00:57:03.225488-06	3	Desparasitación	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
19	2025-10-20 00:57:09.866672-06	3	Desparasitación	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
20	2025-10-20 00:57:33.811224-06	2	Vacunación	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
21	2025-10-20 00:57:42.118099-06	2	Vacunación	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
22	2025-10-20 00:58:02.508686-06	4	Cirugía General	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
23	2025-10-20 00:58:58.978018-06	4	Cirugía General	2	[{"changed": {"fields": ["Imagen"]}}]	8	1
24	2025-10-23 22:31:05.292566-06	6	alejandra23 (cliente)	3		6	1
25	2025-10-23 22:31:05.292606-06	4	magali.2 (cliente)	3		6	1
26	2025-10-23 22:31:23.460144-06	5	magali.1 (cliente)	3		6	1
27	2025-10-23 22:44:11.08468-06	7	alejandra.2 (cliente)	3		6	1
28	2025-10-23 23:08:16.354548-06	8	alejandra.2 (cliente)	3		6	1
29	2025-10-24 18:05:43.85216-06	2	alejandra.1 (cliente)	3		6	1
30	2025-11-03 13:21:36.657048-06	10	magali.3 (veterinario)	2	[{"changed": {"fields": ["Tipo usuario"]}}]	6	1
31	2025-11-03 13:24:37.714533-06	10	magali.3 (veterinario)	2	[{"changed": {"fields": ["Groups"]}}]	6	1
32	2025-11-03 13:25:30.594704-06	10	magali.3 (veterinario)	2	[{"changed": {"fields": ["User permissions"]}}]	6	1
33	2025-11-03 13:28:59.361952-06	10	magali.3 (veterinario)	2	[{"added": {"name": "Perfil de Veterinario", "object": "Perfil Vet: Magal\\u00ed Miranda"}}]	6	1
34	2025-11-03 13:31:23.123604-06	10	magali.3 (veterinario)	2	[{"changed": {"name": "Perfil de Veterinario", "object": "Perfil Vet: Magal\\u00ed Miranda", "fields": ["Bio", "Foto"]}}]	6	1
35	2025-11-03 13:32:19.255325-06	10	magali.3 (veterinario)	2	[{"changed": {"name": "Perfil de Veterinario", "object": "Perfil Vet: Magal\\u00ed Miranda", "fields": ["Servicios"]}}]	6	1
36	2025-11-03 13:32:29.196894-06	10	magali.3 (veterinario)	2	[{"changed": {"name": "Perfil de Veterinario", "object": "Perfil Vet: Magal\\u00ed Miranda", "fields": ["Servicios"]}}]	6	1
37	2025-11-03 16:24:45.098302-06	9	alejandro.2 (cliente)	2	[{"changed": {"fields": ["Username", "Nombre", "Groups", "User permissions"]}}]	6	1
38	2025-11-03 16:25:54.5764-06	9	alejandro.2 (cliente)	2	[]	6	1
39	2025-11-03 16:26:14.90135-06	2	Perfil Vet: Alejandro López	1	[{"added": {}}]	12	1
40	2025-11-03 16:27:13.135129-06	9	alejandro.2 (veterinario)	2	[{"changed": {"fields": ["Tipo usuario"]}}]	6	1
41	2025-11-04 00:31:26.627562-06	25	Cita 25 - magali.24	3		11	1
42	2025-11-04 00:31:26.627605-06	24	Cita 24 - magali.24	3		11	1
43	2025-11-04 00:31:26.627622-06	23	Cita 23 - magali.24	3		11	1
44	2025-11-04 00:31:26.627636-06	21	Cita 21 - magali.24	3		11	1
45	2025-11-04 00:31:26.627649-06	20	Cita 20 - magali.24	3		11	1
46	2025-11-04 00:31:26.627663-06	19	Cita 19 - magali.24	3		11	1
47	2025-11-04 00:31:26.627675-06	14	Cita 14 - magali.24	3		11	1
48	2025-11-04 00:31:26.627687-06	13	Cita 13 - magali.24	3		11	1
49	2025-11-04 00:31:26.627699-06	15	Cita 15 - magali.24	3		11	1
50	2025-11-04 00:31:26.62771-06	17	Cita 17 - magali.24	3		11	1
51	2025-11-04 00:31:26.627722-06	10	Cita 10 - alejandro.2	3		11	1
52	2025-11-04 00:31:26.627734-06	9	Cita 9 - alejandro.2	3		11	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	usuarios	usuario
7	servicios	cita
8	servicios	servicio
9	citas	carritoservicio
10	citas	carrito
11	citas	cita
12	usuarios	veterinarioperfil
13	mascotas	mascota
14	mascotas	historialveterinario
15	mascotas	inmunizacion
16	citas	notaclinica
17	citas	pago
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-10-08 12:07:07.961154-06
2	contenttypes	0002_remove_content_type_name	2025-10-08 12:07:07.966685-06
3	auth	0001_initial	2025-10-08 12:07:08.004672-06
4	auth	0002_alter_permission_name_max_length	2025-10-08 12:07:08.009132-06
5	auth	0003_alter_user_email_max_length	2025-10-08 12:07:08.013445-06
6	auth	0004_alter_user_username_opts	2025-10-08 12:07:08.018326-06
7	auth	0005_alter_user_last_login_null	2025-10-08 12:07:08.02327-06
8	auth	0006_require_contenttypes_0002	2025-10-08 12:07:08.025127-06
9	auth	0007_alter_validators_add_error_messages	2025-10-08 12:07:08.029509-06
10	auth	0008_alter_user_username_max_length	2025-10-08 12:07:08.033897-06
11	auth	0009_alter_user_last_name_max_length	2025-10-08 12:07:08.039075-06
12	auth	0010_alter_group_name_max_length	2025-10-08 12:07:08.044902-06
13	auth	0011_update_proxy_permissions	2025-10-08 12:07:08.049083-06
14	auth	0012_alter_user_first_name_max_length	2025-10-08 12:07:08.053276-06
15	usuarios	0001_initial	2025-10-08 12:07:08.09931-06
16	admin	0001_initial	2025-10-08 12:07:08.123588-06
17	admin	0002_logentry_remove_auto_add	2025-10-08 12:07:08.131642-06
18	admin	0003_logentry_add_action_flag_choices	2025-10-08 12:07:08.138215-06
19	sessions	0001_initial	2025-10-08 12:07:08.151516-06
20	servicios	0001_initial	2025-10-08 12:34:51.041619-06
21	servicios	0002_alter_cita_options_alter_servicio_options_and_more	2025-10-08 12:42:26.516021-06
22	citas	0001_initial	2025-10-08 12:42:26.542091-06
23	usuarios	0002_alter_usuario_telefono	2025-10-09 22:04:15.172099-06
24	servicios	0003_delete_cita	2025-10-10 00:20:27.542991-06
25	citas	0002_carrito_cita_delete_carritoservicio	2025-10-10 00:20:27.625495-06
26	usuarios	0003_remove_usuario_fecha_registro_alter_usuario_telefono_and_more	2025-10-19 15:49:32.932752-06
27	usuarios	0004_usuario_fecha_registro_alter_usuario_telefono_and_more	2025-10-19 15:49:32.962084-06
28	usuarios	0003_alter_usuario_tipo_usuario	2025-10-19 17:05:59.18894-06
29	servicios	0004_alter_servicio_imagen	2025-10-19 18:06:56.43228-06
30	servicios	0005_alter_servicio_imagen	2025-10-19 18:14:41.873798-06
31	usuarios	0003_alter_usuario_options_alter_usuario_email_and_more	2025-10-21 14:48:59.361212-06
32	mascotas	0001_initial	2025-10-22 14:39:35.888632-06
33	mascotas	0002_mascota_codigo_area_mascota_departamento_and_more	2025-10-22 15:09:31.811607-06
34	mascotas	0003_historialveterinario_inmunizacion	2025-10-22 16:23:44.640603-06
35	mascotas	0004_alter_historialveterinario_options_and_more	2025-10-22 16:36:31.296711-06
36	citas	0003_cita_mascota	2025-10-22 18:26:14.36502-06
37	citas	0004_cita_fecha_fin	2025-10-22 20:06:01.303397-06
38	mascotas	0005_historialveterinario_foto	2025-10-23 21:10:48.416813-06
39	usuarios	0004_alter_usuario_first_name_alter_usuario_last_name	2025-10-23 22:29:06.216614-06
40	usuarios	0005_alter_usuario_tipo_usuario_veterinarioperfil	2025-11-03 12:51:30.954557-06
41	citas	0005_cita_actualizado_en_cita_actualizado_por_and_more	2025-11-03 13:03:06.831629-06
42	citas	0006_notaclinica	2025-11-03 15:24:44.267409-06
43	citas	0007_alter_cita_veterinario_pago_cita_pago	2025-11-03 23:55:19.7321-06
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
j941psidcgjmdc4v6r7xacairdihog16	.eJxVjMsOwiAQRf-FtSFAebp07zeQGRikaiAp7cr479qkC93ec859sQjbWuM2aIlzZmcm2el3Q0gPajvId2i3zlNv6zIj3xV-0MGvPdPzcrh_BxVG_damgFUWDQnpzOQBAgnh0EoTtIVcXNBFkgFVlDDeoZzIhwRIFuyUhGbvD9OeN6A:1v6iTl:nhpJBhPX8Ew8s-fqFHd0ZHh5vzdmqIPn9WbD--F_1zc	2025-10-22 22:42:13.483416-06
\.


--
-- Data for Name: mascotas_historialveterinario; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.mascotas_historialveterinario (id, fecha, descripcion, veterinario, diagnostico, creado, mascota_id, foto) FROM stdin;
3	2024-06-12	Chequeo anual y refuerzo de vacunas	Dra. Sofía Ramírez	Salud óptima	2025-10-27 20:50:51.869503-06	6	
4	2025-11-04	El perro cojea de la pata trasera derecha desde ayer. Se cayó de las escaleras del patio.\nTratamiento/Exámenes: Se tomaron radiografías de la pata afectada.\r\nSe inmovilizó la pata con un vendaje espec	Alejandro López	Tibia fracturada en la pata derecha (confirmado con radiografías).	2025-11-03 22:42:20.095232-06	6	
\.


--
-- Data for Name: mascotas_inmunizacion; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.mascotas_inmunizacion (id, edad_anios, rabia, dhpp, lyme, bordetella, lepto, influenza, mascota_id) FROM stdin;
91	1	t	f	f	f	f	f	6
92	2	t	t	f	f	f	f	6
93	3	t	t	t	f	f	f	6
94	4	t	t	f	t	f	f	6
95	5	f	f	f	f	t	t	6
96	6	f	f	f	f	f	f	6
97	7	f	f	f	f	f	f	6
98	8	f	f	f	f	f	f	6
99	9	f	f	f	f	f	f	6
100	10	f	f	f	f	f	f	6
101	11	f	f	f	f	f	f	6
102	12	f	f	f	f	f	f	6
103	13	f	f	f	f	f	f	6
104	14	f	f	f	f	f	f	6
105	15	f	f	f	f	f	f	6
46	1	t	f	f	f	f	f	3
47	2	f	f	f	f	f	f	3
48	3	f	t	f	f	f	f	3
49	4	f	f	t	f	f	f	3
50	5	f	f	f	f	f	f	3
51	6	f	f	f	f	f	f	3
52	7	f	f	f	f	t	f	3
53	8	f	f	f	t	f	f	3
54	9	f	f	f	f	f	f	3
55	10	f	f	f	f	f	f	3
56	11	f	f	f	f	f	f	3
57	12	f	f	f	f	f	f	3
58	13	f	f	f	f	f	f	3
59	14	f	f	f	f	f	f	3
60	15	f	f	f	f	f	f	3
\.


--
-- Data for Name: mascotas_mascota; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.mascotas_mascota (id, nombre, especie, raza, sexo, fecha_nacimiento, peso_kg, color, esterilizado, alergias, foto, creado, actualizado, propietario_id, codigo_area, departamento, direccion_completa, municipio, telefono, zona, condiciones_actuales, veterinario) FROM stdin;
3	Michi	gato	Persa	h	2021-06-25	6.00	Gris	f	Ninguna	mascotas/gatopersa_gjTI4DP.jpg	2025-10-23 23:32:08.388417-06	2025-10-23 23:32:08.388436-06	9	+502	Guatemala	Lote 2 manzana G sector 8 Prados de Villa Hermosa	San Miguel Petapa	36129952	7		
6	Zoe	perro	Golden Retriever	h	2021-04-15	28.40	Dorado	f	Ningua	mascotas/zoe.jpeg	2025-10-27 20:50:51.809544-06	2025-10-27 20:50:51.809565-06	11	+502	Guatemala	Lote 2 manzana G sector 8 Prados de Villa Hermosa	San Miguel Petapa	36129952	7	En buen estado	Dra. Sofía Ramírez
\.


--
-- Data for Name: servicios_servicio; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.servicios_servicio (id, nombre, descripcion, precio, disponible, duracion, imagen) FROM stdin;
1	Consulta general	¿En qué consiste nuestra consulta general? En una revisión completa de tu mascota: examen físico, evaluación de signos vitales, análisis de síntomas, diagnóstico y un plan de tratamiento personalizado.	125.00	t	30	servicios/consultageneral.jpg
3	Desparasitación	Tratamiento completo contra parásitos internos y externos.	75.00	t	15	servicios/desparasitacion.jpg
2	Vacunación	Aplicación de vacunas esenciales para proteger a tu mascota.	90.00	t	20	servicios/vacunacion.jpg
4	Cirugía General	Equipo multidisciplinario capacitado a cargo del cuidado quirúrgico de una amplia variedad de enfermedades que afectan diferentes sistemas y órganos del cuerpo.	400.00	t	90	servicios/cirugia.jpg
5	Traumatología	Servicio de traumatología	100.00	t	50	servicios/traumatologia.jpg
\.


--
-- Data for Name: usuarios_usuario; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios_usuario (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, tipo_usuario, telefono, fecha_registro) FROM stdin;
10	pbkdf2_sha256$1000000$Xsk5Jin5w0m8QdWhLkd8e0$g/jKVYbwQqfMmm1fEMi1p5gqg5Q19Ie3OQ/DzN7PG7E=	2025-11-04 00:59:21.83285-06	f	magali.3	Magalí	Miranda	alejandra19991@hotmail.com	f	t	2025-10-24 16:59:42-06	veterinario	36129952	2025-10-24 16:59:43.359985-06
3	pbkdf2_sha256$1000000$LnVZol21XViKTRjbOI5EcE$kt5onnyVTvVy2vmHH0zI2dgbY2xQyfotsL0hvSsxBF0=	2025-10-09 22:05:56.206408-06	f	paola_mendoza			paolamendoza@gmail.com	f	t	2025-10-08 20:09:31.851454-06	cliente	52196304	2025-10-19 15:49:32.942349-06
1	pbkdf2_sha256$1000000$zyXV12VtHGRXFu6eccZupf$wQnqiik6V7Ac5bPMMOOnTUIDACD6e8BhMyCHgZXIUBA=	2025-11-04 00:31:45.651484-06	t	admin			myvetpet6@gmail.com	t	t	2025-10-08 12:09:11-06	admin	36129952	2025-10-19 15:49:32.942349-06
11	pbkdf2_sha256$1000000$k2oOQwkT5l5Wm5wealpCuG$ulP8tYD42JVdmmsYsIMyLs61Aax31KbKSPqFmMX5H/M=	2025-11-04 00:55:22.6036-06	f	magali.24	Alejandra	Miranda	alejandramglmr@gmail.com	f	t	2025-10-27 20:40:49.641956-06	cliente	36129952	2025-10-27 20:40:49.951-06
9	pbkdf2_sha256$1000000$9jYjDWAVlEHOedaPj9GVIX$+yEhyc/RjhVYOR4PdWUaAieofQYbz+udnTm8oIhJgDs=	2025-11-04 00:58:06.367566-06	f	alejandro.2	Alejandro	López	lopezalejandra2412@gmail.com	f	t	2025-10-23 23:08:34-06	veterinario	36129952	2025-10-23 23:08:35.069967-06
\.


--
-- Data for Name: usuarios_usuario_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios_usuario_groups (id, usuario_id, group_id) FROM stdin;
1	10	2
2	9	2
\.


--
-- Data for Name: usuarios_usuario_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios_usuario_user_permissions (id, usuario_id, permission_id) FROM stdin;
1	10	48
2	10	45
3	10	46
4	10	47
5	9	48
6	9	45
7	9	46
8	9	47
\.


--
-- Data for Name: usuarios_veterinarioperfil; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios_veterinarioperfil (id, colegiado, especialidades, bio, foto, disponible, usuario_id) FROM stdin;
2	6832-Colegio de Médicos Veterinarios de Guatemala	Traumatología y Ortopedia	Dr. Alejandro López especializado en traumatología y ortopedia veterinaria con 12 años de experiencia. Egresado de la Universidad de San Carlos de Guatemala. Experto en tratamiento de fracturas, luxaciones, displasias y rehabilitación post-quirúrgica.	veterinarios/traumatologofoto_CIkL8h1.jpg	t	9
1	5458-Colegio de Médicos Veterinarios de Guatemala	Medicina General y Cirugía de Pequeñas Especies	Dra. Magalí Miranda con más de 8 años de experiencia ejerciendo en la Ciudad de Guatemala. Especializada en diagnóstico y tratamiento de enfermedades de la piel en perros y gatos. Egresada de la Universidad de San Carlos de Guatemala. Apasionada por el bienestar animal y la orientación a dueños de mascotas.	veterinarios/veterinariafoto.jpg	t	10
\.


--
-- Data for Name: usuarios_veterinarioperfil_servicios; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios_veterinarioperfil_servicios (id, veterinarioperfil_id, servicio_id) FROM stdin;
2	1	4
3	2	5
4	1	2
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 3, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 64, true);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: citas_carrito_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.citas_carrito_id_seq', 104, true);


--
-- Name: citas_cita_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.citas_cita_id_seq', 29, true);


--
-- Name: citas_notaclinica_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.citas_notaclinica_id_seq', 1, false);


--
-- Name: citas_pago_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.citas_pago_id_seq', 4, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 52, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 43, true);


--
-- Name: mascotas_historialveterinario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.mascotas_historialveterinario_id_seq', 4, true);


--
-- Name: mascotas_inmunizacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.mascotas_inmunizacion_id_seq', 105, true);


--
-- Name: mascotas_mascota_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.mascotas_mascota_id_seq', 6, true);


--
-- Name: servicios_servicio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.servicios_servicio_id_seq', 5, true);


--
-- Name: usuarios_usuario_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuarios_usuario_groups_id_seq', 2, true);


--
-- Name: usuarios_usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuarios_usuario_id_seq', 11, true);


--
-- Name: usuarios_usuario_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuarios_usuario_user_permissions_id_seq', 8, true);


--
-- Name: usuarios_veterinarioperfil_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuarios_veterinarioperfil_id_seq', 2, true);


--
-- Name: usuarios_veterinarioperfil_servicios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuarios_veterinarioperfil_servicios_id_seq', 4, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: citas_carrito citas_carrito_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_carrito
    ADD CONSTRAINT citas_carrito_pkey PRIMARY KEY (id);


--
-- Name: citas_carrito citas_carrito_usuario_id_servicio_id_9b54b14d_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_carrito
    ADD CONSTRAINT citas_carrito_usuario_id_servicio_id_9b54b14d_uniq UNIQUE (usuario_id, servicio_id);


--
-- Name: citas_cita citas_cita_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_cita
    ADD CONSTRAINT citas_cita_pkey PRIMARY KEY (id);


--
-- Name: citas_notaclinica citas_notaclinica_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_notaclinica
    ADD CONSTRAINT citas_notaclinica_pkey PRIMARY KEY (id);


--
-- Name: citas_pago citas_pago_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_pago
    ADD CONSTRAINT citas_pago_pkey PRIMARY KEY (id);


--
-- Name: citas_pago citas_pago_referencia_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_pago
    ADD CONSTRAINT citas_pago_referencia_key UNIQUE (referencia);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: mascotas_historialveterinario mascotas_historialveterinario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mascotas_historialveterinario
    ADD CONSTRAINT mascotas_historialveterinario_pkey PRIMARY KEY (id);


--
-- Name: mascotas_inmunizacion mascotas_inmunizacion_mascota_id_edad_anios_41a77193_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mascotas_inmunizacion
    ADD CONSTRAINT mascotas_inmunizacion_mascota_id_edad_anios_41a77193_uniq UNIQUE (mascota_id, edad_anios);


--
-- Name: mascotas_inmunizacion mascotas_inmunizacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mascotas_inmunizacion
    ADD CONSTRAINT mascotas_inmunizacion_pkey PRIMARY KEY (id);


--
-- Name: mascotas_mascota mascotas_mascota_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mascotas_mascota
    ADD CONSTRAINT mascotas_mascota_pkey PRIMARY KEY (id);


--
-- Name: mascotas_mascota mascotas_mascota_propietario_id_nombre_3552e34d_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mascotas_mascota
    ADD CONSTRAINT mascotas_mascota_propietario_id_nombre_3552e34d_uniq UNIQUE (propietario_id, nombre);


--
-- Name: servicios_servicio servicios_servicio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.servicios_servicio
    ADD CONSTRAINT servicios_servicio_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario usuarios_usuario_email_0a82e5f9_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_email_0a82e5f9_uniq UNIQUE (email);


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_usuario_id_group_id_4ed5b09e_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_usuario_id_group_id_4ed5b09e_uniq UNIQUE (usuario_id, group_id);


--
-- Name: usuarios_usuario usuarios_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_user_pe_usuario_id_permission_id_217cadcd_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_user_pe_usuario_id_permission_id_217cadcd_uniq UNIQUE (usuario_id, permission_id);


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario usuarios_usuario_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_username_key UNIQUE (username);


--
-- Name: usuarios_veterinarioperfil_servicios usuarios_veterinarioperf_veterinarioperfil_id_ser_e0a978ab_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_veterinarioperfil_servicios
    ADD CONSTRAINT usuarios_veterinarioperf_veterinarioperfil_id_ser_e0a978ab_uniq UNIQUE (veterinarioperfil_id, servicio_id);


--
-- Name: usuarios_veterinarioperfil usuarios_veterinarioperfil_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_veterinarioperfil
    ADD CONSTRAINT usuarios_veterinarioperfil_pkey PRIMARY KEY (id);


--
-- Name: usuarios_veterinarioperfil_servicios usuarios_veterinarioperfil_servicios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_veterinarioperfil_servicios
    ADD CONSTRAINT usuarios_veterinarioperfil_servicios_pkey PRIMARY KEY (id);


--
-- Name: usuarios_veterinarioperfil usuarios_veterinarioperfil_usuario_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_veterinarioperfil
    ADD CONSTRAINT usuarios_veterinarioperfil_usuario_id_key UNIQUE (usuario_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: citas_carrito_servicio_id_55dfbb80; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_carrito_servicio_id_55dfbb80 ON public.citas_carrito USING btree (servicio_id);


--
-- Name: citas_carrito_usuario_id_1b6c5ded; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_carrito_usuario_id_1b6c5ded ON public.citas_carrito USING btree (usuario_id);


--
-- Name: citas_cita_actualizado_por_id_60509fd9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_cita_actualizado_por_id_60509fd9 ON public.citas_cita USING btree (actualizado_por_id);


--
-- Name: citas_cita_mascota_id_57d42afa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_cita_mascota_id_57d42afa ON public.citas_cita USING btree (mascota_id);


--
-- Name: citas_cita_pago_id_df20d78f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_cita_pago_id_df20d78f ON public.citas_cita USING btree (pago_id);


--
-- Name: citas_cita_servicio_id_e2034bca; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_cita_servicio_id_e2034bca ON public.citas_cita USING btree (servicio_id);


--
-- Name: citas_cita_usuario_id_45c0c3ec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_cita_usuario_id_45c0c3ec ON public.citas_cita USING btree (usuario_id);


--
-- Name: citas_cita_veterinario_id_7789b1f4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_cita_veterinario_id_7789b1f4 ON public.citas_cita USING btree (veterinario_id);


--
-- Name: citas_notaclinica_cita_id_57a94602; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_notaclinica_cita_id_57a94602 ON public.citas_notaclinica USING btree (cita_id);


--
-- Name: citas_notaclinica_mascota_id_8529b426; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_notaclinica_mascota_id_8529b426 ON public.citas_notaclinica USING btree (mascota_id);


--
-- Name: citas_notaclinica_veterinario_id_2ecf1a5f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_notaclinica_veterinario_id_2ecf1a5f ON public.citas_notaclinica USING btree (veterinario_id);


--
-- Name: citas_pago_referencia_38e72897_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_pago_referencia_38e72897_like ON public.citas_pago USING btree (referencia varchar_pattern_ops);


--
-- Name: citas_pago_usuario_id_13b6efe3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX citas_pago_usuario_id_13b6efe3 ON public.citas_pago USING btree (usuario_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: mascotas_historialveterinario_mascota_id_eadb0ec2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX mascotas_historialveterinario_mascota_id_eadb0ec2 ON public.mascotas_historialveterinario USING btree (mascota_id);


--
-- Name: mascotas_inmunizacion_mascota_id_4b0a562d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX mascotas_inmunizacion_mascota_id_4b0a562d ON public.mascotas_inmunizacion USING btree (mascota_id);


--
-- Name: mascotas_mascota_propietario_id_05ee2f24; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX mascotas_mascota_propietario_id_05ee2f24 ON public.mascotas_mascota USING btree (propietario_id);


--
-- Name: uniq_usuario_email_ci; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_usuario_email_ci ON public.usuarios_usuario USING btree (lower((email)::text));


--
-- Name: usuarios_usuario_email_0a82e5f9_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_email_0a82e5f9_like ON public.usuarios_usuario USING btree (email varchar_pattern_ops);


--
-- Name: usuarios_usuario_groups_group_id_e77f6dcf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_groups_group_id_e77f6dcf ON public.usuarios_usuario_groups USING btree (group_id);


--
-- Name: usuarios_usuario_groups_usuario_id_7a34077f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_groups_usuario_id_7a34077f ON public.usuarios_usuario_groups USING btree (usuario_id);


--
-- Name: usuarios_usuario_user_permissions_permission_id_4e5c0f2f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_user_permissions_permission_id_4e5c0f2f ON public.usuarios_usuario_user_permissions USING btree (permission_id);


--
-- Name: usuarios_usuario_user_permissions_usuario_id_60aeea80; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_user_permissions_usuario_id_60aeea80 ON public.usuarios_usuario_user_permissions USING btree (usuario_id);


--
-- Name: usuarios_usuario_username_be9def2b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_username_be9def2b_like ON public.usuarios_usuario USING btree (username varchar_pattern_ops);


--
-- Name: usuarios_veterinarioperfil_servicios_servicio_id_75535a39; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_veterinarioperfil_servicios_servicio_id_75535a39 ON public.usuarios_veterinarioperfil_servicios USING btree (servicio_id);


--
-- Name: usuarios_veterinarioperfil_veterinarioperfil_id_cdc664f6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_veterinarioperfil_veterinarioperfil_id_cdc664f6 ON public.usuarios_veterinarioperfil_servicios USING btree (veterinarioperfil_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_carrito citas_carrito_servicio_id_55dfbb80_fk_servicios_servicio_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_carrito
    ADD CONSTRAINT citas_carrito_servicio_id_55dfbb80_fk_servicios_servicio_id FOREIGN KEY (servicio_id) REFERENCES public.servicios_servicio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_carrito citas_carrito_usuario_id_1b6c5ded_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_carrito
    ADD CONSTRAINT citas_carrito_usuario_id_1b6c5ded_fk_usuarios_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_cita citas_cita_actualizado_por_id_60509fd9_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_cita
    ADD CONSTRAINT citas_cita_actualizado_por_id_60509fd9_fk_usuarios_usuario_id FOREIGN KEY (actualizado_por_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_cita citas_cita_mascota_id_57d42afa_fk_mascotas_mascota_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_cita
    ADD CONSTRAINT citas_cita_mascota_id_57d42afa_fk_mascotas_mascota_id FOREIGN KEY (mascota_id) REFERENCES public.mascotas_mascota(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_cita citas_cita_pago_id_df20d78f_fk_citas_pago_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_cita
    ADD CONSTRAINT citas_cita_pago_id_df20d78f_fk_citas_pago_id FOREIGN KEY (pago_id) REFERENCES public.citas_pago(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_cita citas_cita_servicio_id_e2034bca_fk_servicios_servicio_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_cita
    ADD CONSTRAINT citas_cita_servicio_id_e2034bca_fk_servicios_servicio_id FOREIGN KEY (servicio_id) REFERENCES public.servicios_servicio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_cita citas_cita_usuario_id_45c0c3ec_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_cita
    ADD CONSTRAINT citas_cita_usuario_id_45c0c3ec_fk_usuarios_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_cita citas_cita_veterinario_id_7789b1f4_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_cita
    ADD CONSTRAINT citas_cita_veterinario_id_7789b1f4_fk_usuarios_usuario_id FOREIGN KEY (veterinario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_notaclinica citas_notaclinica_cita_id_57a94602_fk_citas_cita_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_notaclinica
    ADD CONSTRAINT citas_notaclinica_cita_id_57a94602_fk_citas_cita_id FOREIGN KEY (cita_id) REFERENCES public.citas_cita(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_notaclinica citas_notaclinica_mascota_id_8529b426_fk_mascotas_mascota_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_notaclinica
    ADD CONSTRAINT citas_notaclinica_mascota_id_8529b426_fk_mascotas_mascota_id FOREIGN KEY (mascota_id) REFERENCES public.mascotas_mascota(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_notaclinica citas_notaclinica_veterinario_id_2ecf1a5f_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_notaclinica
    ADD CONSTRAINT citas_notaclinica_veterinario_id_2ecf1a5f_fk_usuarios_ FOREIGN KEY (veterinario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: citas_pago citas_pago_usuario_id_13b6efe3_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas_pago
    ADD CONSTRAINT citas_pago_usuario_id_13b6efe3_fk_usuarios_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_usuarios_usuario_id FOREIGN KEY (user_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mascotas_historialveterinario mascotas_historialve_mascota_id_eadb0ec2_fk_mascotas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mascotas_historialveterinario
    ADD CONSTRAINT mascotas_historialve_mascota_id_eadb0ec2_fk_mascotas_ FOREIGN KEY (mascota_id) REFERENCES public.mascotas_mascota(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mascotas_inmunizacion mascotas_inmunizacio_mascota_id_4b0a562d_fk_mascotas_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mascotas_inmunizacion
    ADD CONSTRAINT mascotas_inmunizacio_mascota_id_4b0a562d_fk_mascotas_ FOREIGN KEY (mascota_id) REFERENCES public.mascotas_mascota(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mascotas_mascota mascotas_mascota_propietario_id_05ee2f24_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mascotas_mascota
    ADD CONSTRAINT mascotas_mascota_propietario_id_05ee2f24_fk_usuarios_usuario_id FOREIGN KEY (propietario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_groups usuarios_usuario_gro_usuario_id_7a34077f_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_gro_usuario_id_7a34077f_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_group_id_e77f6dcf_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_group_id_e77f6dcf_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_use_permission_id_4e5c0f2f_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_use_permission_id_4e5c0f2f_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_use_usuario_id_60aeea80_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_use_usuario_id_60aeea80_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_veterinarioperfil_servicios usuarios_veterinario_servicio_id_75535a39_fk_servicios; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_veterinarioperfil_servicios
    ADD CONSTRAINT usuarios_veterinario_servicio_id_75535a39_fk_servicios FOREIGN KEY (servicio_id) REFERENCES public.servicios_servicio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_veterinarioperfil usuarios_veterinario_usuario_id_b564398c_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_veterinarioperfil
    ADD CONSTRAINT usuarios_veterinario_usuario_id_b564398c_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_veterinarioperfil_servicios usuarios_veterinario_veterinarioperfil_id_cdc664f6_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_veterinarioperfil_servicios
    ADD CONSTRAINT usuarios_veterinario_veterinarioperfil_id_cdc664f6_fk_usuarios_ FOREIGN KEY (veterinarioperfil_id) REFERENCES public.usuarios_veterinarioperfil(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 6MN6g90zhqriobiuxOucByK4J5iCi0MfuVgCxBLuBfbCjqkg1OvZvD17Vm2QByf

