# Generated by Django 5.2.7 on 2025-10-22 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('conejo', 'Conejo'), ('reptil', 'Reptil'), ('otro', 'Otro')], max_length=20)),
                ('raza', models.CharField(blank=True, max_length=80)),
                ('sexo', models.CharField(choices=[('m', 'Macho'), ('h', 'Hembra'), ('u', 'Desconocido')], default='u', max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('esterilizado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-creado'],
                'unique_together': {('propietario', 'nombre')},
            },
        ),
    ]
