# Generated by Django 5.2.7 on 2025-10-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='codigo_area',
            field=models.CharField(default='+502', max_length=6),
        ),
        migrations.AddField(
            model_name='mascota',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mascota',
            name='direccion_completa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mascota',
            name='municipio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mascota',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mascota',
            name='zona',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
