# Generated by Django 5.2.7 on 2025-10-22 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascota_codigo_area_mascota_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('veterinario', models.CharField(blank=True, max_length=120)),
                ('diagnostico', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='mascotas.mascota')),
            ],
            options={
                'verbose_name': 'Entrada de historial',
                'verbose_name_plural': 'Historial veterinario',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Inmunizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_anios', models.PositiveSmallIntegerField()),
                ('rabia', models.BooleanField(default=False)),
                ('dhpp', models.BooleanField(default=False)),
                ('lyme', models.BooleanField(default=False)),
                ('bordetella', models.BooleanField(default=False)),
                ('lepto', models.BooleanField(default=False)),
                ('influenza', models.BooleanField(default=False)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmunizaciones', to='mascotas.mascota')),
            ],
            options={
                'verbose_name': 'Inmunización',
                'verbose_name_plural': 'Inmunizaciones',
                'ordering': ['edad_anios'],
                'unique_together': {('mascota', 'edad_anios')},
            },
        ),
    ]
