# Generated by Django 5.2.7 on 2025-10-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_historialveterinario_inmunizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialveterinario',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterModelOptions(
            name='inmunizacion',
            options={'ordering': ['edad_anios']},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['-creado']},
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='notas',
            new_name='alergias',
        ),
        migrations.AddField(
            model_name='mascota',
            name='condiciones_actuales',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='veterinario',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
