# Generated by Django 5.2.7 on 2025-10-24 03:10

import mascotas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_alter_historialveterinario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialveterinario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=mascotas.models.HistorialVeterinario.upload_to),
        ),
    ]
