# Generated by Django 5.2.7 on 2025-11-03 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_delete_cita'),
        ('usuarios', '0004_alter_usuario_first_name_alter_usuario_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('veterinario', 'Veterinario'), ('admin', 'Administrador')], default='cliente', max_length=15),
        ),
        migrations.CreateModel(
            name='VeterinarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegiado', models.CharField(blank=True, max_length=50)),
                ('especialidades', models.CharField(blank=True, help_text='Ej.: Cirugía, Dermatología', max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='veterinarios/')),
                ('disponible', models.BooleanField(default=True)),
                ('servicios', models.ManyToManyField(blank=True, related_name='veterinarios', to='servicios.servicio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_veterinario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Veterinario',
                'verbose_name_plural': 'Perfiles de Veterinario',
            },
        ),
    ]
